//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_V_OnnxlREeaQsuJXrUQkwgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Planear, Monitorear y Controlar el Proceso_F7616B84_5b0da200_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_b8wyNm4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Definir Contexto y Fuentes de Requerimientos_736D9522_6df92b00_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_yoMobG4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Analizar el Negocio_9747D148_91d36726_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_uETmYm4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Analizar Interesados_3646B9C8_30d24fa6_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwgActivity"]="./../../core.base_ID/capabilitypatterns/resources/BA e Ing Req PMI ValApr Exportado_FCBBA028_fcbba028_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_TGhxU24kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Identificar Motivadores del Proyecto_3DC4D64B_38506c29_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Análisis de Negocio e Ingenieria de Requerimientos_E0904F0E_443c858a_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_wOEINW4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Definir el_E1FCABF0_dc8841ce_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_7cyqdG4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Estimar el Esfuerzo de Implementación_45EB9252_40772830_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_XR-eUSRHEeaMa6qeU-BtWgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Administrar Requerimientos de la Solucion_6DB18474_d15dbaf0_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_jRb2dW7kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Concluir Proyecto Tecnico de Requerimientos y Análisis de Negoci_7F429B13_79ce30f1_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,__-NCUCdmEeaocvbgkF3xZQActivity"]="./../../core.base_ID/capabilitypatterns/resources/Configurar el proceso y_DD613B56_410d71d2_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_2HD76W4kEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Analizar y Documentar los Requerimientos_7C78BFB5_77045593_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_H5mGK27lEeasReGETR2LgAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Obtener Requerimientos_86297C57_80b51235_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_6DeEoVi7EeaDrPSXsRaepg,_bKVZ0XOBEeaWIYCXReRDCAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Componentes de Diseño_D6F46F65_f8f4ad77_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_aiAv0j1uEeam7LhYvpDjVgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Actividad nuevo_2_F9C085BD_5d6cbc39_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_hT5c8SRMEeaMa6qeU-BtWgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Valoración de la solución implantada_DBB7E9E_7167b51a_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_0ecNsW4jEeasReGETR2LgA,_2eT-AXOlEeaWIYCXReRDCAActivity"]="./../../core.base_ID/capabilitypatterns/resources/Evaluar y validar_BAE2F7BD_b56e8d9b_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_rs8cjidOEeaXN7JCPxh1VwActivity"]="./../../core.base_ID/capabilitypatterns/resources/PRB_69DBA880_cd87defc_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_6DeEoVi7EeaDrPSXsRaepgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Diseño_70015342_d3ad89be_Activity.jpeg"
contentPage.processPage.imageFiles["_V_OnTBlREeaQsuJXrUQkwg,_V_E2gBlREeaQsuJXrUQkwgActivity"]="./../../core.base_ID/capabilitypatterns/resources/Validar y Aprobar Entregables_534E1F83_b6fa55ff_Activity.jpeg"
contentPage.processPage.imageFiles["_n6hDMSKtEeaTVrlJIawuTQActivity"]="./../../core.base_ID/capabilitypatterns/resources/PRB_43E447D2_43e447d2_Activity.jpeg"
contentPage.processPage.elementUrls["_yoMoVG4kEeasReGETR2LgA"] = ["Matriz de Trazabilidad ","core.base_ID/workproducts/Matriz de Trazabilidad_BC6CA566.html"];
contentPage.processPage.elementUrls["_uETmaG4kEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_rs8cgydOEeaXN7JCPxh1Vw"] = ["Estimación de tiempo para actividades de desarrollo y pruebas","core.base_ID/workproducts/Estimación de tiempo para actividades de desarrollo y pruebas_FC322B37.html"];
contentPage.processPage.elementUrls["_U5dWAXOfEeaWIYCXReRDCA"] = ["Matriz de Estimación basada en Puntos de Función","core.base_ID/workproducts/Matriz de Estimación basada en Puntos de Función_5AB668D4.html"];
contentPage.processPage.elementUrls["_v1fzwEevEeaiTq1ZJ4wJLA"] = ["2. Administrar y reportar el desempeño del proceso ","core.base_ID/tasks/Administrar y reportar el desempeño del proceso_18EC07E0.html"];
contentPage.processPage.elementUrls["_b8wyM24kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_V_OnTBlREeaQsuJXrUQkwg"] = ["Análisis de Negocio e Ingeniería de Requerimientos para Claro SA","core.base_ID/capabilitypatterns/BA e Ing Req PMI ValApr Exportado_FCBBA028.html"];
contentPage.processPage.elementUrls["_TGhxVW4kEeasReGETR2LgA"] = ["Inventario de fuentes","core.base_ID/workproducts/Inventario de fuentes_1955CA77.html"];
contentPage.processPage.elementUrls["_T3imBHOfEeaWIYCXReRDCA"] = ["Estimación de Esfuerzo basada en PCUs","core.base_ID/workproducts/Estimación de Esfuerzo basada en PCUs_375D70B9.html"];
contentPage.processPage.elementUrls["_v1fzxUevEeaiTq1ZJ4wJLA"] = ["Consolidados de Administración de Ajustes","core.base_ID/workproducts/Consolidados de Administración de Ajustes_D55C0D65.html"];
contentPage.processPage.elementUrls["_vgFtcSKtEeaTVrlJIawuTQ"] = ["Inventario de Fuentes","core.base_ID/workproducts/Inventario de Fuentes_9DC3AED8.html"];
contentPage.processPage.elementUrls["_rsyrjydOEeaXN7JCPxh1Vw"] = ["PRB_T3_Cierre del FSP","core.base_ID/tasks/PRB_T3_Cierre del FSP_D4BF543C.html"];
contentPage.processPage.elementUrls["_v1fzxEevEeaiTq1ZJ4wJLA"] = ["Resultados de Inspecciones","core.base_ID/workproducts/Resultados de Inspecciones_D1367808.html"];
contentPage.processPage.elementUrls["_tKJvoD1uEeam7LhYvpDjVg"] = ["1. Radicar y Generar Numero de Consecutivo","core.base_ID/tasks/Radicar y Generar Numero de Consecutivo_72CC4673.html"];
contentPage.processPage.elementUrls["_AwTJA0elEeaiTq1ZJ4wJLA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_TGhxWG4kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_2HD77G4kEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_HAFbsDllEeaNotA8WqGP2A"] = ["PRB_T2_Apoyo al usuario en elaboración del FSP","core.base_ID/tasks/PRB_T2_Apoyo al usuario en elaboración del FSP_C778D7E2.html"];
contentPage.processPage.elementUrls["_6kal0XOnEeaWIYCXReRDCA"] = ["Experto TI del sistema","core.base_ID/roles/Experto TI del sistema_CD44954F.html"];
contentPage.processPage.elementUrls["_H5mGK27lEeasReGETR2LgA"] = ["Obtener Requerimientos de la Solucion","core.base_ID/capabilitypatterns/Obtener Requerimientos_86297C57.html"];
contentPage.processPage.elementUrls["_HgidYDllEeaNotA8WqGP2A"] = ["PRB_T2_Control de calidad del FSP","core.base_ID/tasks/PRB_T2_Control de calidad del FSP_D34FD927.html"];
contentPage.processPage.elementUrls["_nPj-cDlmEeaNotA8WqGP2A"] = ["PRB_T2_Apoyo al usuario en elaboración del FSP","core.base_ID/tasks/PRB_T2_Apoyo al usuario en elaboración del FSP_C778D7E2.html"];
contentPage.processPage.elementUrls["_NNIyQ0enEeaiTq1ZJ4wJLA"] = ["Actas de Recorridos con acuerdos de ajustes a Realizar y plan de seguimiento","core.base_ID/workproducts/Actas de Recorridos con acuerdos de ajustes a Realizar y plan de_188D9DAB.html"];
contentPage.processPage.elementUrls["_wOEINm4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_uQUusiKtEeaTVrlJIawuTQ"] = ["Informe de avance","core.base_ID/workproducts/Informe de avance_1C423F5B.html"];
contentPage.processPage.elementUrls["_uETmZW4kEeasReGETR2LgA"] = ["Líder de desarrollo TI gerencias impactadas","core.base_ID/roles/Líder de desarrollo TI gerencias impactadas_1DDC2F7A.html"];
contentPage.processPage.elementUrls["_IVp0AEepEeaiTq1ZJ4wJLA"] = ["2. Elaborar y/o Refinar Configuración del Proceso de Requerimientos y Análisis de Negocio","core.base_ID/tasks/Elaborar y o Refinar Configuración del Proceso de Requerimientos_D9DAEA7D.html"];
contentPage.processPage.elementUrls["_LSe-EHOGEeaWIYCXReRDCA"] = ["Diseño de la cápsula.","core.base_ID/tasks/Diseño de la cápsula_AAF1FC7B.html"];
contentPage.processPage.elementUrls["_7uMjSHOlEeaWIYCXReRDCA"] = ["Alcance de la Solución","core.base_ID/workproducts/Alcance de la Solución_E7B2873.html"];
contentPage.processPage.elementUrls["_vEbsMiKtEeaTVrlJIawuTQ"] = ["FSP preliminar","core.base_ID/workproducts/FSP preliminar_886FB6B0.html"];
contentPage.processPage.elementUrls["_7ornkkenEeaiTq1ZJ4wJLA"] = ["Reportes de requerimientos implementados","core.base_ID/workproducts/Reportes de requerimientos implementados_7D1E7FA4.html"];
contentPage.processPage.elementUrls["_uQUusSKtEeaTVrlJIawuTQ"] = ["Informe de incidentes","core.base_ID/workproducts/Informe de incidentes_12A8C7B0.html"];
contentPage.processPage.elementUrls["_H5mGJG7lEeasReGETR2LgA"] = ["Cronograma de Actividades","core.base_ID/workproducts/Cronograma de Actividades_BE409D68.html"];
contentPage.processPage.elementUrls["_SLKf6iQjEeafHYiLU-YTMg"] = ["Artefactos de análisis de negocio e ingeniería de requerimientos configurados para la solicitud","core.base_ID/workproducts/Artefactos de análisis de negocio e ingeniería de requerimientos_6D55EFF0.html"];
contentPage.processPage.elementUrls["_2HD7824kEeasReGETR2LgA"] = ["Restricciones y supuestos identificados en las acitvidades de obtención de requerimientos","core.base_ID/workproducts/Restricciones y supuestos identificados en las actividades de ob_230AEAF0.html"];
contentPage.processPage.elementUrls["_yoMoeW4kEeasReGETR2LgA"] = ["Reglas de Negocio_1","core.base_ID/workproducts/Reglas de Negocio_BDF27FD6.html"];
contentPage.processPage.elementUrls["_jRb2dm7kEeasReGETR2LgA"] = ["Preparación del paquete de requerimientos","core.base_ID/tasks/Preparación del paquete de requerimientos_E0B1B820.html"];
contentPage.processPage.elementUrls["_H5mGI27lEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_yoMobW4kEeasReGETR2LgA"] = ["Documento de Visión","core.base_ID/workproducts/Documento de Visión_D5C1D34A.html"];
contentPage.processPage.elementUrls["_b8wyNm4kEeasReGETR2LgA"] = ["Definir contexto y fuentes de Informacion","core.base_ID/capabilitypatterns/Definir Contexto y Fuentes de Requerimientos_736D9522.html"];
contentPage.processPage.elementUrls["_2HD79W4kEeasReGETR2LgA"] = ["Arquitectura de TI","core.base_ID/roles/Arquitectura de TI_614DAAA8.html"];
contentPage.processPage.elementUrls["_RtP1gUepEeaiTq1ZJ4wJLA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_yoMoY24kEeasReGETR2LgA"] = ["Glosario base","core.base_ID/workproducts/Glosario base_F57FEC80.html"];
contentPage.processPage.elementUrls["_PJslkkenEeaiTq1ZJ4wJLA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_EJNowEepEeaiTq1ZJ4wJLA"] = ["1. Recibir y Registrar Solicitud Formal de Trabajo de Requerimientos y Análisis de Negocio","core.base_ID/tasks/Recibir y Registrar Solicitud Formal de Trabajo de Requerimiento_A20D89BC.html"];
contentPage.processPage.elementUrls["_TGhxWW4kEeasReGETR2LgA"] = ["Identificar y Trazar los Motivadores de Negocio para la Solicitud","core.base_ID/tasks/Identificar y Trazar los Motivadores de Negocio para la Solicitu_9F93EDEE.html"];
contentPage.processPage.elementUrls["_2HD78m4kEeasReGETR2LgA"] = ["3. Definir restricciones y supuestos","core.base_ID/tasks/Definir restricciones y supuestos_B633BA6B.html"];
contentPage.processPage.elementUrls["_yoMoam4kEeasReGETR2LgA"] = ["6. Definir y Trazar necesidades del negocio","core.base_ID/tasks/Definir y Trazar necesidades del negocio_59726E43.html"];
contentPage.processPage.elementUrls["_-0NcUHOBEeaWIYCXReRDCA"] = ["Diseño del subsistema.","core.base_ID/tasks/Diseño del Subsistema_B6E90B85.html"];
contentPage.processPage.elementUrls["_yoMocG4kEeasReGETR2LgA"] = ["Coordinador del servicio - Claro","core.base_ID/roles/Coordinador del servicio - Claro_C1E36866.html"];
contentPage.processPage.elementUrls["__-NCUCdmEeaocvbgkF3xZQ"] = ["Configurar el Proceso y Definir Entregables","core.base_ID/capabilitypatterns/Configurar el proceso y_DD613B56.html"];
contentPage.processPage.elementUrls["_NNRqQkepEeaiTq1ZJ4wJLA"] = ["Plan de Administración de Requerimientos","core.base_ID/workproducts/Plan de Administración de Requerimientos_C5AAED30.html"];
contentPage.processPage.elementUrls["_rs8cjSdOEeaXN7JCPxh1Vw"] = ["Informe de avance","core.base_ID/workproducts/Informe de avance_1C423F5B.html"];
contentPage.processPage.elementUrls["_IVp0A0epEeaiTq1ZJ4wJLA"] = ["Hoja de Configuración elaborada o actualizada ","core.base_ID/workproducts/Hoja de Configuración elaborada o actualizada_51779391.html"];
contentPage.processPage.elementUrls["_yoMob24kEeasReGETR2LgA"] = ["1. Analizar el Proceso y Reglas de Negocio","core.base_ID/tasks/Analizar el Proceso y Reglas de Negocio_C40037A7.html"];
contentPage.processPage.elementUrls["_yoMoZW4kEeasReGETR2LgA"] = ["Diagramas de proceso","core.base_ID/workproducts/Diagramas de proceso_F71964DF.html"];
contentPage.processPage.elementUrls["_rs8cgSdOEeaXN7JCPxh1Vw"] = ["Análisis de Negocio e Ingeniería de Requerimientos","core.base_ID/tasks/Análisis de Negocio e Ingeniería de Requerimientos_1064AE8B.html"];
contentPage.processPage.elementUrls["_7uMjRXOlEeaWIYCXReRDCA"] = ["Gerente de proyecto de PMO","core.base_ID/roles/Gerente de proyecto de PMO_BB316903.html"];
contentPage.processPage.elementUrls["_EJNowUepEeaiTq1ZJ4wJLA"] = ["Coodinador de requerimientos","core.base_ID/roles/Coodinador de requerimientos_28FB1810.html"];
contentPage.processPage.elementUrls["_wOEIN24kEeasReGETR2LgA"] = ["Definir el Problema y la Visión de la Solución","core.base_ID/tasks/Definir el Problema y la Visión de la Solución_99B29CDD.html"];
contentPage.processPage.elementUrls["_TGhxV24kEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_NNIyQEenEeaiTq1ZJ4wJLA"] = ["1. Verificar internamente la calidad de los entregables","core.base_ID/tasks/Verificar internamente la calidad de los entregables_C328097B.html"];
contentPage.processPage.elementUrls["_EJNowkepEeaiTq1ZJ4wJLA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_2HD79m4kEeasReGETR2LgA"] = ["Experto TI del sistema","core.base_ID/roles/Experto TI del sistema_CD44954F.html"];
contentPage.processPage.elementUrls["_AwYBgUelEeaiTq1ZJ4wJLA"] = ["Cronograma de Trabajo (creado o actualizado)","core.base_ID/workproducts/Cronograma de Trabajo creado o actualizado_D5B5892B.html"];
contentPage.processPage.elementUrls["_wOEIMW4kEeasReGETR2LgA"] = ["Documento de Visión","core.base_ID/workproducts/Documento de Visión_D5C1D34A.html"];
contentPage.processPage.elementUrls["_vSjnwiKtEeaTVrlJIawuTQ"] = ["FSP validado y aprobado","core.base_ID/workproducts/FSP validado y aprobado_6361673A.html"];
contentPage.processPage.elementUrls["_H5mGKm7lEeasReGETR2LgA"] = ["Contexto e Inventario de Fuentes de Información","core.base_ID/workproducts/Contexto e Inventario de Fuentes de Información_9C4A8314.html"];
contentPage.processPage.elementUrls["_b8wyOW4kEeasReGETR2LgA"] = ["Técnicas de Obtención Configuradas para cada Fuente","core.base_ID/workproducts/Técnicas de Obtención Configuradas para cada Fuente_6E88BDBC.html"];
contentPage.processPage.elementUrls["_yoMoX24kEeasReGETR2LgA"] = ["Necesidades del negocio","core.base_ID/workproducts/Necesidades del negocio_97C11A3A.html"];
contentPage.processPage.elementUrls["_XR-eUSRHEeaMa6qeU-BtWg"] = ["Administrar Requerimientos de la Solucion","core.base_ID/capabilitypatterns/Administrar Requerimientos de la Solucion_6DB18474.html"];
contentPage.processPage.elementUrls["_rs8chSdOEeaXN7JCPxh1Vw"] = ["FSP Cerrado y aprobado","core.base_ID/workproducts/FSP Cerrado y aprobado_2462C71.html"];
contentPage.processPage.elementUrls["_jRb2cW7kEeasReGETR2LgA"] = ["Entregables definidos en la matriz de configuración de proceso, construidos o actualizados.","core.base_ID/workproducts/Entregables definidos en la matriz de configuración de proceso c_351EBD7F.html"];
contentPage.processPage.elementUrls["_2HD75W4kEeasReGETR2LgA"] = ["Modelo de Requerimientos","core.base_ID/workproducts/Modelo de Requerimientos_91721A80.html"];
contentPage.processPage.elementUrls["_wOEIOG4kEeasReGETR2LgA"] = ["Coodinador de requerimientos","core.base_ID/roles/Coodinador de requerimientos_28FB1810.html"];
contentPage.processPage.elementUrls["_0ecNsW4jEeasReGETR2LgA"] = ["Análisis de Negocio e Ingenieria de Requerimientos ","core.base_ID/capabilitypatterns/Análisis de Negocio e Ingenieria de Requerimientos_E0904F0E.html"];
contentPage.processPage.elementUrls["_2HD75m4kEeasReGETR2LgA"] = ["Especificación de Caso de Uso_1","core.base_ID/workproducts/Especificación de Caso de Uso_F6465F47.html"];
contentPage.processPage.elementUrls["_H5mGJW7lEeasReGETR2LgA"] = ["Proceso Configurado","core.base_ID/workproducts/Proceso Configurado_23AB5A54.html"];
contentPage.processPage.elementUrls["_SMNBtCQjEeafHYiLU-YTMg"] = ["Estimación de tiempo para actividades de desarrollo y pruebas","core.base_ID/workproducts/Estimación de tiempo para actividades de desarrollo y pruebas_FC322B37.html"];
contentPage.processPage.elementUrls["_yoMoW24kEeasReGETR2LgA"] = ["Inventario de fuentes (hoja documentación)","core.base_ID/workproducts/Inventario de fuentes hoja documentación_5081989F.html"];
contentPage.processPage.elementUrls["_AwTJAkelEeaiTq1ZJ4wJLA"] = ["Coordinador del servicio - Claro","core.base_ID/roles/Coordinador del servicio - Claro_C1E36866.html"];
contentPage.processPage.elementUrls["_jRb2eW7kEeasReGETR2LgA"] = ["Hoja de Configuración elaborada o actualizada ","core.base_ID/workproducts/Hoja de Configuración elaborada o actualizada_51779391.html"];
contentPage.processPage.elementUrls["_npjy0DlmEeaNotA8WqGP2A"] = ["PRB_T2_Control de calidad del FSP","core.base_ID/tasks/PRB_T2_Control de calidad del FSP_D34FD927.html"];
contentPage.processPage.elementUrls["_nPj-djlmEeaNotA8WqGP2A"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_416A4DA8.html"];
contentPage.processPage.elementUrls["_uETmYW4kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_rsyrgSdOEeaXN7JCPxh1Vw"] = ["FSP cerrado","core.base_ID/workproducts/FSP cerrado_404CCBB7.html"];
contentPage.processPage.elementUrls["_xDAaAzlcEeaNotA8WqGP2A"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_SLKf4SQjEeafHYiLU-YTMg"] = ["Ingeniero de requerimientos","core.base_ID/roles/Ingeniero de requerimientos_D3593F8A.html"];
contentPage.processPage.elementUrls["_uETmZ24kEeasReGETR2LgA"] = ["Analizar interesados","core.base_ID/tasks/Analizar interesados_B2AC8EA7.html"];
contentPage.processPage.elementUrls["_hT5c8SRMEeaMa6qeU-BtWg"] = ["Valoración de la solución implantada","core.base_ID/capabilitypatterns/Valoración de la solución implantada_DBB7E9E.html"];
contentPage.processPage.elementUrls["_znf_YkenEeaiTq1ZJ4wJLA"] = ["Coordinador del servicio - Claro","core.base_ID/roles/Coordinador del servicio - Claro_C1E36866.html"];
contentPage.processPage.elementUrls["_U5dWAHOfEeaWIYCXReRDCA"] = ["2. Estimar basado en puntos función","core.base_ID/tasks/Estimar basado en puntos funcion_2F12AD9.html"];
contentPage.processPage.elementUrls["_2HD7_m4kEeasReGETR2LgA"] = ["Documento de Visión","core.base_ID/workproducts/Documento de Visión_D5C1D34A.html"];
contentPage.processPage.elementUrls["_nPj-dTlmEeaNotA8WqGP2A"] = ["Objetivos estratégicos de la gerencia solicitante","core.base_ID/workproducts/Objetivos estratégicos de la gerencia solicitante_B543D7EA.html"];
contentPage.processPage.elementUrls["_H5mGJ27lEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_-qts0XOnEeaWIYCXReRDCA"] = ["Requerimientos de Transición","core.base_ID/workproducts/Requerimientos de Transición_390522B0.html"];
contentPage.processPage.elementUrls["_rs8ckCdOEeaXN7JCPxh1Vw"] = ["PRB_T4_Estimación etapas de desarrollo y pruebas","core.base_ID/tasks/PRB_T4_Estimación etapas de desarrollo y pruebas_DBECCA5A.html"];
contentPage.processPage.elementUrls["_PJslkEenEeaiTq1ZJ4wJLA"] = ["2. Validar y aprobar los entregables","core.base_ID/tasks/Validar y aprobar los entregables_48690B63.html"];
contentPage.processPage.elementUrls["_2HD7524kEeasReGETR2LgA"] = ["4. Documentar Requerimientos No Funcionales","core.base_ID/tasks/Documentar Requerimientos No Funcionales_3C5288FB.html"];
contentPage.processPage.elementUrls["_o-7BtEeoEeaiTq1ZJ4wJLA"] = ["Solución implantada","core.base_ID/workproducts/Solución implantada_C10FA9C7.html"];
contentPage.processPage.elementUrls["_yoMoe24kEeasReGETR2LgA"] = ["Caso de Negocios y rol del proyecto ","core.base_ID/workproducts/Caso de Negocios y rol del proyecto_F501642E.html"];
contentPage.processPage.elementUrls["_T3imA3OfEeaWIYCXReRDCA"] = ["Matriz de Estimación basada en Puntos de Caso de Uso","core.base_ID/workproducts/Matriz de Estimación basada en Puntos de Caso de Uso_695020AD.html"];
contentPage.processPage.elementUrls["_rsyrgidOEeaXN7JCPxh1Vw"] = ["Matriz de configuración de proceso","core.base_ID/workproducts/Matriz de configuración de proceso_8DB44C79.html"];
contentPage.processPage.elementUrls["_rsyrhidOEeaXN7JCPxh1Vw"] = ["Artefactos de análisis de negocio e ingeniería de requerimientos configurados para la solicitud","core.base_ID/workproducts/Artefactos de análisis de negocio e ingeniería de requerimientos_6D55EFF0.html"];
contentPage.processPage.elementUrls["_nPj-czlmEeaNotA8WqGP2A"] = [" Histórico de briefs en curso","core.base_ID/workproducts/Histórico de briefs en curso_12DECBF9.html"];
contentPage.processPage.elementUrls["_jRb2dW7kEeasReGETR2LgA"] = ["Finalizar Analisis de Negocio e Ingenieria de Requerimientos","core.base_ID/capabilitypatterns/Concluir Proyecto Tecnico de Requerimientos y Análisis de Negoci_7F429B13.html"];
contentPage.processPage.elementUrls["_b8wyNG4kEeasReGETR2LgA"] = ["Inventario de fuentes","core.base_ID/workproducts/Inventario de fuentes_1955CA77.html"];
contentPage.processPage.elementUrls["_rs8cjidOEeaXN7JCPxh1Vw"] = ["Gestión de Solicitudes en el PRB","core.base_ID/capabilitypatterns/PRB_69DBA880.html"];
contentPage.processPage.elementUrls["_znf_ZUenEeaiTq1ZJ4wJLA"] = ["Plan de Administración de Requerimientos","core.base_ID/workproducts/Plan de Administración de Requerimientos_C5AAED30.html"];
contentPage.processPage.elementUrls["_yoMoem4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_NNIyQkenEeaiTq1ZJ4wJLA"] = ["Producto de Trabajo ","core.base_ID/workproducts/Producto de Trabajo_F2B56307.html"];
contentPage.processPage.elementUrls["_rs8cjydOEeaXN7JCPxh1Vw"] = ["PRB_T4_Estimación etapa de requerimientos","core.base_ID/tasks/PRB_T4_Estimación etapa de requerimientos_15825A5C.html"];
contentPage.processPage.elementUrls["_o-7BskeoEeaiTq1ZJ4wJLA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_2HD7-m4kEeasReGETR2LgA"] = ["2. Documentación y Modelamiento de requerimientos","core.base_ID/tasks/Documentación y Modelamiento de requerimientos_91DCDF24.html"];
contentPage.processPage.elementUrls["_3XFPgEenEeaiTq1ZJ4wJLA"] = ["2. Administrar la trazabilidad de los requerimientos","core.base_ID/tasks/Administrar la trazabilidad de los requerimientos_6A7BC2AF.html"];
contentPage.processPage.elementUrls["_RtP1gEepEeaiTq1ZJ4wJLA"] = ["4. Definir la estrategia de análisis de negocio y Requerimientos","core.base_ID/tasks/Definir la estrategia de análisis de negocio y Requerimientos_62EAADB2.html"];
contentPage.processPage.elementUrls["_yoMoXG4kEeasReGETR2LgA"] = ["3. Analizar documentación relacionada con el negocio","core.base_ID/tasks/Analizar Documentación relacionada con el Negocio_59B1B424.html"];
contentPage.processPage.elementUrls["_yoMoYG4kEeasReGETR2LgA"] = ["5. Definir el caso de negocio","core.base_ID/tasks/Definir el caso de negocio_E90522F7.html"];
contentPage.processPage.elementUrls["_V_OnnxlREeaQsuJXrUQkwg"] = ["Planear, Monitorear y  Controlar el Proceso","core.base_ID/capabilitypatterns/Planear, Monitorear y Controlar el Proceso_F7616B84.html"];
contentPage.processPage.elementUrls["_7uMjR3OlEeaWIYCXReRDCA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_znf_YUenEeaiTq1ZJ4wJLA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_EJNoxkepEeaiTq1ZJ4wJLA"] = ["Estimación de esfuerzo para la elaboración de la Configuración del Proceso","core.base_ID/workproducts/Estimación de esfuerzo para la elaboración de la Configuración d_FACF2427.html"];
contentPage.processPage.elementUrls["_7uMjTnOlEeaWIYCXReRDCA"] = ["Documento de Evaluación de soluciones propuestas ","core.base_ID/workproducts/Documento de Evaluación de soluciones propuestas_13A0857E.html"];
contentPage.processPage.elementUrls["_rs8ckydOEeaXN7JCPxh1Vw"] = ["Esimación de tiempo y esfuerzo","core.base_ID/workproducts/Esimación de tiempo y esfuerzo_843CA0CB.html"];
contentPage.processPage.elementUrls["_yoMobG4kEeasReGETR2LgA"] = ["Analizar el negocio","core.base_ID/capabilitypatterns/Analizar el Negocio_9747D148.html"];
contentPage.processPage.elementUrls["_BvaVQEeoEeaiTq1ZJ4wJLA"] = ["5. Mantenimiento de requerimientos para la reutilización","core.base_ID/tasks/Mantenimiento de requerimientos para la reutilización_92031394.html"];
contentPage.processPage.elementUrls["_V_E2gBlREeaQsuJXrUQkwg"] = ["Validar  y Aprobar Entregables","core.base_ID/capabilitypatterns/Validar y Aprobar Entregables_534E1F83.html"];
contentPage.processPage.elementUrls["_HAFbtjllEeaNotA8WqGP2A"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_416A4DA8.html"];
contentPage.processPage.elementUrls["_6kal03OnEeaWIYCXReRDCA"] = ["Solución seleccionada","core.base_ID/workproducts/Solución seleccionada_AA673A8B.html"];
contentPage.processPage.elementUrls["_T3imAHOfEeaWIYCXReRDCA"] = ["1. Estimar basado en PCU ","core.base_ID/tasks/Estimar basado en PCU_1A262893.html"];
contentPage.processPage.elementUrls["_yoMoXW4kEeasReGETR2LgA"] = ["Coodinador de requerimientos","core.base_ID/roles/Coodinador de requerimientos_28FB1810.html"];
contentPage.processPage.elementUrls["_2HD7_W4kEeasReGETR2LgA"] = ["Especificación Requerimientos No Funcionales","core.base_ID/workproducts/Especificación Requerimientos No Funcionales_14DF4687.html"];
contentPage.processPage.elementUrls["_2HD7-W4kEeasReGETR2LgA"] = ["Necesidades del negocio","core.base_ID/workproducts/Necesidades del negocio_97C11A3A.html"];
contentPage.processPage.elementUrls["_OX0zQSdnEeaocvbgkF3xZQ"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_wOEINW4kEeasReGETR2LgA"] = ["Definir el Problema y la Vision de la Solucion","core.base_ID/capabilitypatterns/Definir el_E1FCABF0.html"];
contentPage.processPage.elementUrls["_H5mGIm7lEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_o-7BtUeoEeaiTq1ZJ4wJLA"] = ["Métricas de los indicadores definidos en la solicitud","core.base_ID/workproducts/Métricas de los indicadores definidos en la solicitud_416D65BA.html"];
contentPage.processPage.elementUrls["_o-7BtkeoEeaiTq1ZJ4wJLA"] = ["Indicadores o características definidas en T2_Proceso PRB1","core.base_ID/workproducts/Indicadores o características definidas en T2_Proceso PRB1_C6675443.html"];
contentPage.processPage.elementUrls["_vSjnwSKtEeaTVrlJIawuTQ"] = ["Matriz de configuración de proceso","core.base_ID/workproducts/Matriz de configuración de proceso_8DB44C79.html"];
contentPage.processPage.elementUrls["_PJslk0enEeaiTq1ZJ4wJLA"] = ["Acta de Aprobación Final","core.base_ID/workproducts/Acta de Aprobación Final_F11D3955.html"];
contentPage.processPage.elementUrls["_yoMoVm4kEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_rs8clidOEeaXN7JCPxh1Vw"] = ["Listado de observaciones y o cambios al FSP","core.base_ID/workproducts/Listado de observaciones y o cambios al FSP_66C8F4E3.html"];
contentPage.processPage.elementUrls["_v1fzw0evEeaiTq1ZJ4wJLA"] = ["Actas de Recorridos","core.base_ID/workproducts/Actas de Recorridos_D8E673E1.html"];
contentPage.processPage.elementUrls["_7uMjRnOlEeaWIYCXReRDCA"] = ["Arquitectura de TI","core.base_ID/roles/Arquitectura de TI_614DAAA8.html"];
contentPage.processPage.elementUrls["_6kal1HOnEeaWIYCXReRDCA"] = ["Evaluación del nivel de preparación de la organización","core.base_ID/workproducts/Evaluación del nivel de preparación de la organización_4A1AAE73.html"];
contentPage.processPage.elementUrls["_vShLgCKtEeaTVrlJIawuTQ"] = ["PRB_T3_Recorrido sobre el FSP","core.base_ID/tasks/PRB_T3_Recorrido sobre el FSP_60E52966.html"];
contentPage.processPage.elementUrls["_7ornkEenEeaiTq1ZJ4wJLA"] = ["3. Organizar requerimientos","core.base_ID/tasks/Organizar requerimientos_E7007F3.html"];
contentPage.processPage.elementUrls["_jRb2eG7kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_rsyrjidOEeaXN7JCPxh1Vw"] = ["PRB_T3_Recorrido sobre el FSP","core.base_ID/tasks/PRB_T3_Recorrido sobre el FSP_60E52966.html"];
contentPage.processPage.elementUrls["_xkd-0D1uEeam7LhYvpDjVg"] = ["3. Administrar Dependencias","core.base_ID/tasks/Administrar Dependencias_6135A862.html"];
contentPage.processPage.elementUrls["_yoMoYm4kEeasReGETR2LgA"] = ["2. Analizar los Sistemas actuales del Negocio","core.base_ID/tasks/Analizar los Sistemas actuales del Negocio_5B7C3EA0.html"];
contentPage.processPage.elementUrls["_uETmY24kEeasReGETR2LgA"] = ["Matriz de Configuración del Proceso","core.base_ID/workproducts/Matriz de Configuración del Proceso_1890D87E.html"];
contentPage.processPage.elementUrls["_7uMjTXOlEeaWIYCXReRDCA"] = ["Matriz de Trazabilidad ","core.base_ID/workproducts/Matriz de Trazabilidad_BC6CA566.html"];
contentPage.processPage.elementUrls["_HWgYEHODEeaWIYCXReRDCA"] = ["Diseño de Clase.","core.base_ID/tasks/Diseño de Clase_6284035B.html"];
contentPage.processPage.elementUrls["_2HD78G4kEeasReGETR2LgA"] = ["1. Definir alcance de la solución","core.base_ID/tasks/Definir alcance de la solución_33ADFBB0.html"];
contentPage.processPage.elementUrls["_2HD7-G4kEeasReGETR2LgA"] = ["Especificación Funcional","core.base_ID/workproducts/Especificación Funcional_98F280A2.html"];
contentPage.processPage.elementUrls["_vgFtciKtEeaTVrlJIawuTQ"] = ["Esimación de tiempo y esfuerzo","core.base_ID/workproducts/Esimación de tiempo y esfuerzo_843CA0CB.html"];
contentPage.processPage.elementUrls["_yoMoeG4kEeasReGETR2LgA"] = ["Inventario de fuentes (hoja sistemas)","core.base_ID/workproducts/Inventario de fuentes hoja sistemas_24A17C68.html"];
contentPage.processPage.elementUrls["_7uMjSnOlEeaWIYCXReRDCA"] = ["Especificación de Requerimientos de Software (SRS) ","core.base_ID/workproducts/Especificación de Requerimientos de Software SRS_66907264.html"];
contentPage.processPage.elementUrls["_HAFbtTllEeaNotA8WqGP2A"] = ["Objetivos estratégicos de la gerencia solicitante","core.base_ID/workproducts/Objetivos estratégicos de la gerencia solicitante_B543D7EA.html"];
contentPage.processPage.elementUrls["_b8wyNW4kEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_yoMobm4kEeasReGETR2LgA"] = ["Gerente de proyecto de PMO","core.base_ID/roles/Gerente de proyecto de PMO_BB316903.html"];
contentPage.processPage.elementUrls["_b8wyMm4kEeasReGETR2LgA"] = ["Contexto de la Solución","core.base_ID/workproducts/Contexto de la Solución_C6059773.html"];
contentPage.processPage.elementUrls["_o-7BsUeoEeaiTq1ZJ4wJLA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_znf_Z0enEeaiTq1ZJ4wJLA"] = ["Repositorio de Requerimientos Actualizado","core.base_ID/workproducts/Repositorio de Requerimientos Actualizado_F5E4C0CF.html"];
contentPage.processPage.elementUrls["_AwTJAUelEeaiTq1ZJ4wJLA"] = ["Coodinador de requerimientos","core.base_ID/roles/Coodinador de requerimientos_28FB1810.html"];
contentPage.processPage.elementUrls["_6DeEoVi7EeaDrPSXsRaepg"] = ["Diseño","core.base_ID/capabilitypatterns/Diseño_70015342.html"];
contentPage.processPage.elementUrls["_7ornkUenEeaiTq1ZJ4wJLA"] = ["Coodinador de requerimientos","core.base_ID/roles/Coodinador de requerimientos_28FB1810.html"];
contentPage.processPage.elementUrls["_2HD7724kEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["__CNIIkenEeaiTq1ZJ4wJLA"] = ["Repositorio de requerimientos priorizado","core.base_ID/workproducts/Repositorio de requerimientos priorizado_C6FE3E8C.html"];
contentPage.processPage.elementUrls["_znf_YEenEeaiTq1ZJ4wJLA"] = ["1. Administrar los Requerimientos de la solución","core.base_ID/tasks/Administrar los Requerimientos de la solución_E4ED0207.html"];
contentPage.processPage.elementUrls["_v1fzwUevEeaiTq1ZJ4wJLA"] = ["Control Calidad","core.base_ID/roles/Control Calidad_F2B094BD.html"];
contentPage.processPage.elementUrls["__CNIIUenEeaiTq1ZJ4wJLA"] = ["Líder de desarrollo TI gerencias impactadas","core.base_ID/roles/Líder de desarrollo TI gerencias impactadas_1DDC2F7A.html"];
contentPage.processPage.elementUrls["_EJNoxUepEeaiTq1ZJ4wJLA"] = ["Confirmación de Cambio de Estado de la Solicitud enviado a Interesado(s)","core.base_ID/workproducts/Confirmación de Cambio de Estado de la Solicitud enviado a Inter_C9F20A88.html"];
contentPage.processPage.elementUrls["_v1fzwkevEeaiTq1ZJ4wJLA"] = ["Cronograma actualizado","core.base_ID/workproducts/Cronograma actualizado_176F8943.html"];
contentPage.processPage.elementUrls["_IVp0AkepEeaiTq1ZJ4wJLA"] = ["Matriz de Configuración del Proceso","core.base_ID/workproducts/Matriz de Configuración del Proceso_1890D87E.html"];
contentPage.processPage.elementUrls["_jRb2d27kEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_uETmYm4kEeasReGETR2LgA"] = ["Analizar Interesados","core.base_ID/capabilitypatterns/Analizar Interesados_3646B9C8.html"];
contentPage.processPage.elementUrls["_NNIyREenEeaiTq1ZJ4wJLA"] = ["Entregables inspeccionados con ajustes sugeridos","core.base_ID/workproducts/Entregables inspeccionados con ajustes sugeridos_C63921C7.html"];
contentPage.processPage.elementUrls["_uETmaW4kEeasReGETR2LgA"] = ["Matriz de configuración de proceso (Hoja Interesados)","core.base_ID/workproducts/Matriz de configuración de proceso Hoja Interesados_E61C65B2.html"];
contentPage.processPage.elementUrls["_7uMjQnOlEeaWIYCXReRDCA"] = ["3. Validar conformidad entre las posibles soluciones y los requerimientos ","core.base_ID/tasks/Validar conformidad entre las posibles soluciones y los requerim_6CFB6171.html"];
contentPage.processPage.elementUrls["_rsyrhSdOEeaXN7JCPxh1Vw"] = ["Cronograma","core.base_ID/workproducts/Cronograma_31A056F3.html"];
contentPage.processPage.elementUrls["_vvI2ECKtEeaTVrlJIawuTQ"] = ["PRB_T4_Estimación etapas de desarrollo y pruebas","core.base_ID/tasks/PRB_T4_Estimación etapas de desarrollo y pruebas_DBECCA5A.html"];
contentPage.processPage.elementUrls["_vgFGYCKtEeaTVrlJIawuTQ"] = ["PRB_T4_Estimación etapa de requerimientos","core.base_ID/tasks/PRB_T4_Estimación etapa de requerimientos_15825A5C.html"];
contentPage.processPage.elementUrls["_v1fzxkevEeaiTq1ZJ4wJLA"] = ["Reporte de Desempeño del Proceso","core.base_ID/workproducts/Reporte de Desempeño del Proceso_B66D4296.html"];
contentPage.processPage.elementUrls["_rsyrkCdOEeaXN7JCPxh1Vw"] = ["Informe de incidentes","core.base_ID/workproducts/Informe de incidentes_12A8C7B0.html"];
contentPage.processPage.elementUrls["_vEbsMyKtEeaTVrlJIawuTQ"] = ["FSP Cerrado y aprobado","core.base_ID/workproducts/FSP Cerrado y aprobado_2462C71.html"];
contentPage.processPage.elementUrls["_7uMjQXOlEeaWIYCXReRDCA"] = ["2. Evaluar Alternativas de Solución Propuestas","core.base_ID/tasks/Evaluar Alternativas de Solución Propuestas_8C567719.html"];
contentPage.processPage.elementUrls["_NNRqQUepEeaiTq1ZJ4wJLA"] = ["Plan de Administración de Requerimientos Base","core.base_ID/workproducts/Plan de Administración de Requerimientos Base_45CA3EA7.html"];
contentPage.processPage.elementUrls["_rs8ciydOEeaXN7JCPxh1Vw"] = ["Líder de requerimientos Claro","core.base_ID/roles/Líder de requerimientos Claro_47EAE97F.html"];
contentPage.processPage.elementUrls["_ggls0HOBEeaWIYCXReRDCA"] = ["Diseño de caso de uso.","core.base_ID/tasks/Diseño de caso de uso_BF006889.html"];
contentPage.processPage.elementUrls["_znf_Y0enEeaiTq1ZJ4wJLA"] = ["Lider de requerimientos","core.base_ID/roles/Lider de requerimientos_F201AE9E.html"];
contentPage.processPage.elementUrls["_AwYBgEelEeaiTq1ZJ4wJLA"] = ["Matriz de Configuración del Proceso","core.base_ID/workproducts/Matriz de Configuración del Proceso_1890D87E.html"];
contentPage.processPage.elementUrls["_7uMjQHOlEeaWIYCXReRDCA"] = ["1. Asociar Requerimientos a Alternativas de Solución","core.base_ID/tasks/Asociar Requerimientos a Alternativas de Solución_7758E57.html"];
contentPage.processPage.elementUrls["_TGhxU24kEeasReGETR2LgA"] = ["Identificar motivadores de la Solicitud","core.base_ID/capabilitypatterns/Identificar Motivadores del Proyecto_3DC4D64B.html"];
contentPage.processPage.elementUrls["_yoMoYW4kEeasReGETR2LgA"] = ["4. Capturar Vocabulario Común","core.base_ID/tasks/Capturar Vocabulario Común_BE704D81.html"];
contentPage.processPage.elementUrls["_7cyqdG4kEeasReGETR2LgA"] = ["Estimar el esfuerzo de Implementación","core.base_ID/capabilitypatterns/Estimar el Esfuerzo de Implementación_45EB9252.html"];
contentPage.processPage.elementUrls["_SLKf5yQjEeafHYiLU-YTMg"] = ["Usuario área de negocio líder de la iniciativa","core.base_ID/roles/Usuario área de negocio líder de la iniciativa_77E3C185.html"];
contentPage.processPage.elementUrls["_TGhxVm4kEeasReGETR2LgA"] = ["Objetivos y Problemas del Negocio","core.base_ID/workproducts/Objetivos y Problemas del Negocio_196F265A.html"];
contentPage.processPage.elementUrls["_HgidYTllEeaNotA8WqGP2A"] = ["Documento con observaciones y/o modificaciones.","core.base_ID/workproducts/Documento con observaciones y o modificaciones_32A4637D.html"];
contentPage.processPage.elementUrls["_HAFbszllEeaNotA8WqGP2A"] = [" Histórico de briefs en curso","core.base_ID/workproducts/Histórico de briefs en curso_12DECBF9.html"];
contentPage.processPage.elementUrls["_uQUHoCKtEeaTVrlJIawuTQ"] = ["Análisis de Negocio e Ingeniería de Requerimientos.","core.base_ID/tasks/Análisis de Negocio e Ingeniería de Requerimientos_1064AE8B.html"];
contentPage.processPage.elementUrls["_yoMod24kEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_6kal0nOnEeaWIYCXReRDCA"] = ["Entregables definidos en la matriz de configuración del proceso de la solicitud","core.base_ID/workproducts/Entregables definidos en la matriz de configuración del proceso _8B712410.html"];
contentPage.processPage.elementUrls["_nPj-dDlmEeaNotA8WqGP2A"] = ["Proceso de negocio","core.base_ID/workproducts/Proceso de negocio_58DCFB87.html"];
contentPage.processPage.elementUrls["_nPj-cjlmEeaNotA8WqGP2A"] = ["Brief","core.base_ID/workproducts/Brief_233CE15A.html"];
contentPage.processPage.elementUrls["_H5mGJm7lEeasReGETR2LgA"] = ["Coordinador del servicio - Claro","core.base_ID/roles/Coordinador del servicio - Claro_C1E36866.html"];
contentPage.processPage.elementUrls["_RtP1gkepEeaiTq1ZJ4wJLA"] = ["Inventario de fuentes","core.base_ID/workproducts/Inventario de fuentes_1955CA77.html"];
contentPage.processPage.elementUrls["_b8wyN24kEeasReGETR2LgA"] = ["Documento de contexto de la gerencia","core.base_ID/workproducts/Documento de contexto de la gerencia_6A3A4B08.html"];
contentPage.processPage.elementUrls["_2HD74m4kEeasReGETR2LgA"] = ["Matriz de Configuración del Proceso","core.base_ID/workproducts/Matriz de Configuración del Proceso_1890D87E.html"];
contentPage.processPage.elementUrls["_yoMoWm4kEeasReGETR2LgA"] = ["Modelo de Proceso del Negocio actual o futuro","core.base_ID/workproducts/Modelo de Proceso del Negocio actual o futuro_3700283A.html"];
contentPage.processPage.elementUrls["_NNIyRUenEeaiTq1ZJ4wJLA"] = ["Consolidados de Administración de Ajustes","core.base_ID/workproducts/Consolidados de Administración de Ajustes_D55C0D65.html"];
contentPage.processPage.elementUrls["_yoMoUm4kEeasReGETR2LgA"] = ["Proceso de negocio","core.base_ID/workproducts/Proceso de negocio_CD8D59C7.html"];
contentPage.processPage.elementUrls["_znf_ZkenEeaiTq1ZJ4wJLA"] = ["Requerimientos","core.base_ID/workproducts/Requerimientos_2576820E.html"];
contentPage.processPage.elementUrls["_H5mGKW7lEeasReGETR2LgA"] = ["Obtener Información ","core.base_ID/tasks/Obtener Información_A8A2BB4.html"];
contentPage.processPage.elementUrls["_jRb2c27kEeasReGETR2LgA"] = ["Lider de requerimientos","core.base_ID/roles/Lider de requerimientos_F201AE9E.html"];
contentPage.processPage.elementUrls["_T3imAnOfEeaWIYCXReRDCA"] = ["Requerimientos aprobados","core.base_ID/workproducts/Requerimientos aprobados_F09362C9.html"];
contentPage.processPage.elementUrls["_rsyriydOEeaXN7JCPxh1Vw"] = ["FSP preliminar","core.base_ID/workproducts/FSP preliminar_886FB6B0.html"];
contentPage.processPage.elementUrls["_yoMoUW4kEeasReGETR2LgA"] = ["Glosario","core.base_ID/workproducts/Glosario_9003B0BA.html"];
contentPage.processPage.elementUrls["_U5dWAnOfEeaWIYCXReRDCA"] = ["Estimación de Esfuerzo basada en Puntos Función","core.base_ID/workproducts/Estimación de Esfuerzo basada en Puntos Función_F8D5DB45.html"];
contentPage.processPage.elementUrls["_T3imAXOfEeaWIYCXReRDCA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_27tcwHOGEeaWIYCXReRDCA"] = ["Revisar el Diseño.","core.base_ID/tasks/Revisar el Diseño_CD798FB.html"];
contentPage.processPage.elementUrls["_yoMoZG4kEeasReGETR2LgA"] = ["Cuadro de Mando Medio Ponderado","core.base_ID/workproducts/Cuadro de Mando Medio Ponderado_656C04FD.html"];
contentPage.processPage.elementUrls["_o-7Bt0eoEeaiTq1ZJ4wJLA"] = ["Documento de Visión","core.base_ID/workproducts/Documento de Visión_D5C1D34A.html"];
contentPage.processPage.elementUrls["_2HD76W4kEeasReGETR2LgA"] = ["Analizar y Documentar los Requerimientos de la Solucion","core.base_ID/capabilitypatterns/Analizar y Documentar los Requerimientos_7C78BFB5.html"];
contentPage.processPage.elementUrls["_b8wyOG4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_TGhxVG4kEeasReGETR2LgA"] = ["Matriz de Trazabilidad ","core.base_ID/workproducts/Matriz de Trazabilidad_BC6CA566.html"];
contentPage.processPage.elementUrls["_7uMjSXOlEeaWIYCXReRDCA"] = ["Caso del Negocio ","core.base_ID/workproducts/Caso del Negocio_6442BC68.html"];
contentPage.processPage.elementUrls["_7uMjTHOlEeaWIYCXReRDCA"] = ["Alternativas de solución identificadas","core.base_ID/workproducts/Alternativas de solución identificadas_E9703B6C.html"];
contentPage.processPage.elementUrls["_znf_ZEenEeaiTq1ZJ4wJLA"] = ["Documento de Visión","core.base_ID/workproducts/Documento de Visión_D5C1D34A.html"];
contentPage.processPage.elementUrls["_2eT-AXOlEeaWIYCXReRDCA"] = ["Evaluar y Validar Alternativas de Solución ","core.base_ID/capabilitypatterns/Evaluar y validar_BAE2F7BD.html"];
contentPage.processPage.elementUrls["_yoMoaG4kEeasReGETR2LgA"] = ["Líder de desarrollo TI gerencias impactadas","core.base_ID/roles/Líder de desarrollo TI gerencias impactadas_1DDC2F7A.html"];
contentPage.processPage.elementUrls["_wOEIM24kEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_NNIyQUenEeaiTq1ZJ4wJLA"] = ["Control Calidad","core.base_ID/roles/Control Calidad_F2B094BD.html"];
contentPage.processPage.elementUrls["_vSjnwyKtEeaTVrlJIawuTQ"] = ["Listado de observaciones y o cambios al FSP","core.base_ID/workproducts/Listado de observaciones y o cambios al FSP_66C8F4E3.html"];
contentPage.processPage.elementUrls["_yoMoWW4kEeasReGETR2LgA"] = ["Documento de contexto","core.base_ID/workproducts/Documento de contexto_9ECC02D2.html"];
contentPage.processPage.elementUrls["_uQUusCKtEeaTVrlJIawuTQ"] = ["Cronograma","core.base_ID/workproducts/Cronograma_31A056F3.html"];
contentPage.processPage.elementUrls["__CNIIEenEeaiTq1ZJ4wJLA"] = ["4. Priorizar Requerimientos","core.base_ID/tasks/Priorizar Requerimientos_F7446D7F.html"];
contentPage.processPage.elementUrls["_aiAv0j1uEeam7LhYvpDjVg"] = ["Gestión de Control de Cambios","core.base_ID/capabilitypatterns/Actividad nuevo_2_F9C085BD.html"];
contentPage.processPage.elementUrls["_yoMoXm4kEeasReGETR2LgA"] = ["Inventario de fuentes (hoja interesados)","core.base_ID/workproducts/Inventario de fuentes hoja interesados_83579E81.html"];
contentPage.processPage.elementUrls["_jRb2dG7kEeasReGETR2LgA"] = ["Paquete de Requerimientos para entrega","core.base_ID/workproducts/Paquete de Requerimientos para entrega_7D9DE9B7.html"];
contentPage.processPage.elementUrls["_vSjnwCKtEeaTVrlJIawuTQ"] = ["FSP a ser validado","core.base_ID/workproducts/FSP a ser validado_91D1AFDD.html"];
contentPage.processPage.elementUrls["_7uMjRHOlEeaWIYCXReRDCA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_2HD76m4kEeasReGETR2LgA"] = ["Resultado de la obtención de requerimientos","core.base_ID/workproducts/Resultado de la obtención de requerimientos_AD016242.html"];
contentPage.processPage.elementUrls["_EJNow0epEeaiTq1ZJ4wJLA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_b8wyMW4kEeasReGETR2LgA"] = ["Definir contexto e inventario de fuentes de requerimientos de la solución","core.base_ID/tasks/Definir contexto e inventario de fuentes de requerimientos de la_80D33AE3.html"];
contentPage.processPage.elementUrls["_yoMocm4kEeasReGETR2LgA"] = ["Objetivos del negocio","core.base_ID/workproducts/Objetivos del negocio_D63E6DF5.html"];
contentPage.processPage.elementUrls["_nPj-cTlmEeaNotA8WqGP2A"] = ["Líder de requerimientos gerencia TI","core.base_ID/roles/Líder de requerimientos gerencia TI_40052493.html"];
contentPage.processPage.elementUrls["_vEbsMCKtEeaTVrlJIawuTQ"] = ["PRB_T3_Cierre del FSP","core.base_ID/tasks/PRB_T3_Cierre del FSP_D4BF543C.html"];
contentPage.processPage.elementUrls["_H5mGIW7lEeasReGETR2LgA"] = ["Técnicas de Obtención Definidas","core.base_ID/workproducts/Técnicas de Obtención Definidas_458429F4.html"];
contentPage.processPage.elementUrls["_2HD78W4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_3XFPgUenEeaiTq1ZJ4wJLA"] = ["Matriz de Trazabilidad ","core.base_ID/workproducts/Matriz de Trazabilidad_BC6CA566.html"];
contentPage.processPage.elementUrls["_IVp0AUepEeaiTq1ZJ4wJLA"] = ["Coordinador del servicio - Claro","core.base_ID/roles/Coordinador del servicio - Claro_C1E36866.html"];
contentPage.processPage.elementUrls["_H5mGKG7lEeasReGETR2LgA"] = ["Propuesta de Especificación Funcional (FSP)","core.base_ID/workproducts/Propuesta de Especificación Funcional FSP_56123F7F.html"];
contentPage.processPage.elementUrls["_yoMoc24kEeasReGETR2LgA"] = ["Tablero de Control","core.base_ID/workproducts/Tablero de Control_A05FB236.html"];
contentPage.processPage.elementUrls["_HAFbtDllEeaNotA8WqGP2A"] = ["Proceso de negocio","core.base_ID/workproducts/Proceso de negocio_58DCFB87.html"];
contentPage.processPage.elementUrls["_v_-GMD1uEeam7LhYvpDjVg"] = ["2. Evaluación de Aprovación o Rechazo de la Solicitud","core.base_ID/tasks/Evaluación de Aprovación o Rechazo de la Solicitud_222B72B0.html"];
contentPage.processPage.elementUrls["_rs8cgidOEeaXN7JCPxh1Vw"] = ["FSP validado y aprobado","core.base_ID/workproducts/FSP validado y aprobado_6361673A.html"];
contentPage.processPage.elementUrls["_rsyrkidOEeaXN7JCPxh1Vw"] = ["Inventario de Fuentes","core.base_ID/workproducts/Inventario de Fuentes_9DC3AED8.html"];
contentPage.processPage.elementUrls["_2HD76G4kEeasReGETR2LgA"] = ["Inventario de fuentes","core.base_ID/workproducts/Inventario de fuentes_1955CA77.html"];
contentPage.processPage.elementUrls["_n6hDMSKtEeaTVrlJIawuTQ"] = ["PRB","core.base_ID/capabilitypatterns/PRB_43E447D2.html"];
contentPage.processPage.elementUrls["_bKVZ0XOBEeaWIYCXReRDCA"] = ["Componentes de Diseño","core.base_ID/capabilitypatterns/Componentes de Diseño_D6F46F65.html"];
contentPage.processPage.elementUrls["_uETmam4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_-qts0HOnEeaWIYCXReRDCA"] = ["5. Definir requerimientos de transición hacia la nueva solución","core.base_ID/tasks/Definir requerimientos de transición hacia la nueva solución_61B78521.html"];
contentPage.processPage.elementUrls["_o-7BsEeoEeaiTq1ZJ4wJLA"] = ["Valorar la efectividad de la solución implantada","core.base_ID/tasks/Valorar la efectividad de la solución implantada_1A9767AB.html"];
contentPage.processPage.elementUrls["_rs8chCdOEeaXN7JCPxh1Vw"] = ["FSP a ser validado","core.base_ID/workproducts/FSP a ser validado_91D1AFDD.html"];
contentPage.processPage.elementUrls["_jRb2cm7kEeasReGETR2LgA"] = ["Matriz de Configuración del Proceso","core.base_ID/workproducts/Matriz de Configuración del Proceso_1890D87E.html"];
contentPage.processPage.elementUrls["_npjy0TlmEeaNotA8WqGP2A"] = ["Documento con observaciones y/o modificaciones.","core.base_ID/workproducts/Documento con observaciones y o modificaciones_32A4637D.html"];
contentPage.processPage.elementUrls["_wOEIMm4kEeasReGETR2LgA"] = ["Experto TI del sistema","core.base_ID/roles/Experto TI del sistema_CD44954F.html"];
contentPage.processPage.elementUrls["_b8wyO24kEeasReGETR2LgA"] = ["Líder de requerimientos TI gerencias impactadas","core.base_ID/roles/Líder de requerimientos TI gerencias impactadas_84AEBE0B.html"];
contentPage.processPage.elementUrls["_fedE8HOCEeaWIYCXReRDCA"] = ["Diseño de la Operación.","core.base_ID/tasks/Diseño de la Operación_E9EB2F42.html"];
contentPage.processPage.elementUrls["_uETmZm4kEeasReGETR2LgA"] = ["Inventario de fuentes (hoja interesados)","core.base_ID/workproducts/Inventario de fuentes hoja interesados_83579E81.html"];
contentPage.processPage.elementUrls["_HAFbsTllEeaNotA8WqGP2A"] = ["Líder de requerimientos gerencia TI","core.base_ID/roles/Líder de requerimientos gerencia TI_40052493.html"];
contentPage.processPage.elementUrls["_EJNoxEepEeaiTq1ZJ4wJLA"] = ["Solicitud con Estado actualizado","core.base_ID/workproducts/Solicitud con Estado actualizado_59747EB3.html"];
contentPage.processPage.elementUrls["_SLKf5CQjEeafHYiLU-YTMg"] = ["Líder de requerimientos Claro","core.base_ID/roles/Líder de requerimientos Claro_47EAE97F.html"];
contentPage.processPage.elementUrls["_rs8ciidOEeaXN7JCPxh1Vw"] = ["Ingeniero de requerimientos","core.base_ID/roles/Ingeniero de requerimientos_D3593F8A.html"];
contentPage.processPage.elementUrls["_rs8clCdOEeaXN7JCPxh1Vw"] = ["Usuario área de negocio líder de la iniciativa","core.base_ID/roles/Usuario área de negocio líder de la iniciativa_77E3C185.html"];
contentPage.processPage.elementUrls["_o-7Bs0eoEeaiTq1ZJ4wJLA"] = ["Requerimientos documentados","core.base_ID/workproducts/Requerimientos documentados_846A039B.html"];
contentPage.processPage.elementUrls["_AwTJAEelEeaiTq1ZJ4wJLA"] = ["1. Planear actividades","core.base_ID/tasks/Planear actividades_88C76608.html"];
contentPage.processPage.elementUrls["_yoMoV24kEeasReGETR2LgA"] = ["Inventario de fuentes","core.base_ID/workproducts/Inventario de fuentes_1955CA77.html"];
contentPage.processPage.elementUrls["_6kal0HOnEeaWIYCXReRDCA"] = ["4. Evaluar nivel de preparación de la organización","core.base_ID/tasks/Evaluar nivel de preparación de la organización_52BBEA8B.html"];
contentPage.processPage.elementUrls["_TGhxUm4kEeasReGETR2LgA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_HAFbsjllEeaNotA8WqGP2A"] = ["Brief","core.base_ID/workproducts/Brief_233CE15A.html"];
contentPage.processPage.elementUrls["_7uMjQ3OlEeaWIYCXReRDCA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_2HD7624kEeasReGETR2LgA"] = ["Especificación de Requerimientos de Software (SRS) ","core.base_ID/workproducts/Especificación de Requerimientos de Software SRS_66907264.html"];
contentPage.processPage.elementUrls["_LlFhgSdJEeaXN7JCPxh1Vw"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_7uMjS3OlEeaWIYCXReRDCA"] = ["Requerimientos","core.base_ID/workproducts/Requerimientos_2576820E.html"];
contentPage.processPage.elementUrls["_gPBZ8SdJEeaXN7JCPxh1Vw"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_vgFtcCKtEeaTVrlJIawuTQ"] = ["FSP cerrado","core.base_ID/workproducts/FSP cerrado_404CCBB7.html"];
contentPage.processPage.elementUrls["_PJsllEenEeaiTq1ZJ4wJLA"] = ["Registro de Aprobación Tácita","core.base_ID/workproducts/Registro de Aprobación Tácita_EC219FD5.html"];
contentPage.processPage.elementUrls["_PJslkUenEeaiTq1ZJ4wJLA"] = ["Usuario de Negocio Responsable de la Iniciativa","core.base_ID/roles/Usuario de Negocio Responsable de la Iniciativa_84CDA28.html"];
contentPage.processPage.elementUrls["_2HD7-24kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_yoMoaW4kEeasReGETR2LgA"] = ["Ingeniero de Requerimientos","core.base_ID/roles/Ingeniero de Requerimientos_7F4E9F4A.html"];
contentPage.processPage.elementUrls["_o-7BuEeoEeaiTq1ZJ4wJLA"] = ["Evaluación de la efectvidadde la solución implantada","core.base_ID/workproducts/Evaluación de la efectvidadde la solución implantada_5277FD9E.html"];
contentPage.processPage.elementUrls["_BvaVQUeoEeaiTq1ZJ4wJLA"] = ["Todos los entregables de Requerimientos ","core.base_ID/workproducts/Todos los entregables de Requerimientos_E98272EC.html"];
contentPage.processPage.elementUrls["_NNRqQEepEeaiTq1ZJ4wJLA"] = ["3. Definir plan de administración de requerimientos","core.base_ID/tasks/Definir plan de administración de requerimientos_4BC9B959.html"];
contentPage.processPage.elementUrls["_2HD79G4kEeasReGETR2LgA"] = ["Requerimientos","core.base_ID/workproducts/Requerimientos_2576820E.html"];
